from enum import Enum

VARIABLE = 'variable declaration'
CONSTANT = 'constant declaration'
FUNCTION = 'function declaration'
CLASS = 'class declaration'
FOR = 'for loop'
WHILE = 'while loop'
ASSIGNMENT = 'assignment operation'
BITWISE = 'bitwise operation'
MATHEMATICAL = 'mathematical operation'
CASTING = 'casting'
INPUT = 'input'
OUTPUT = 'output'
ASSERTION = 'assertion'
LIBRARY = 'libraries'
COMMENT = 'comment'
CONDITIONAL = 'conditional operation'
FILE = 'file system'
GIT = 'git operation'
INTERACTIVE = 'activate interactive'
MOUSE = 'activate mouse'
MEMBERSHIP = 'membership operation'
IDE = 'ide operation'
ARRAY = 'array operation'